#!/bin/bash

rm "$HOME/.config/fish"
rm "$HOME/.config/nvim"
rm "$HOME/.tmux.conf"
rm "$HOME/.wezterm.lua"
rm "$HOME/.config/ghostty"
rm "$HOME/.config/zed/settings.json"
rm "$HOME/.config/zed/keymap.json"
rm -rf "$HOME/.config/zed/themes"

ln -sf "$PWD/fish" "$HOME/.config/fish"
ln -sf "$PWD/nvim" "$HOME/.config/nvim"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/wezterm.lua" "$HOME/.wezterm.lua"
ln -sf "$PWD/ghostty" "$HOME/.config/ghostty"
ln -sf "$PWD/zed/settings.json" "$HOME/.config/zed/settings.json"
ln -sf "$PWD/zed/keymap.json" "$HOME/.config/zed/keymap.json"
ln -sf "$PWD/zed/themes" "$HOME/.config/zed/themes"
